[package]
name = "arx-gas"
description = "Gas metering for the Arx blockchain"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
arx-framework = { workspace = true }
arx-gas-algebra-ext = { workspace = true }
arx-protocol-constants = { workspace = true }
arx-package-builder = { workspace = true }
arx-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-stdlib = { workspace = true }
move-table-extension = { workspace = true }
move-vm-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
testing = ["move-stdlib/testing", "arx-protocol-constants/testing"]

[[bin]]
name = "arx-gas-gen-update-proposal"
path = "src/bin/gen_proposal.rs"
