[package]
name = "arx-storage-interface"
description = "Arx storage interface"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
arx-crypto = { workspace = true }
arx-logger = { workspace = true }
arx-metrics-core = { workspace = true }
arx-scratchpad = { workspace = true }
arx-secure-net = { workspace = true }
arx-state-view = { workspace = true }
arx-types = { workspace = true }
arx-vm = { workspace = true }
bcs = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
arx-types = { workspace = true, features = ["fuzzing"] }
assert_unordered = { workspace = true }

[features]
default = []
fuzzing = ["arx-types/fuzzing"]
