[package]
name = "arx-netcore"
description = "Arx netcore"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
arx-memsocket = { workspace = true }
arx-proxy = { workspace = true }
arx-types = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[dev-dependencies]
arx-memsocket = { workspace = true }
arx-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["arx-memsocket/fuzzing", "arx-types/fuzzing"]
testing = ["arx-memsocket/testing"]
