[package]
name = "arx-backup-cli"
description = "Backup CLI"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
arx-config = { workspace = true }
arx-crypto = { workspace = true }
arx-db = { workspace = true }
arx-executor = { workspace = true }
arx-executor-test-helpers = { workspace = true }
arx-executor-types = { workspace = true }
arx-infallible = { workspace = true }
arx-jellyfish-merkle = { workspace = true }
arx-logger = { workspace = true }
arx-push-metrics = { workspace = true }
arx-scratchpad = { workspace = true }
arx-storage-interface = { workspace = true }
arx-temppath = { workspace = true }
arx-types = { workspace = true }
arx-vm = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
arx-backup-service = { workspace = true }
arx-config = { workspace = true }
arx-db = { workspace = true }
arx-executor-test-helpers = { workspace = true }
arx-proptest-helpers = { workspace = true }
arx-storage-interface = { workspace = true }
proptest = { workspace = true }
warp = { workspace = true }

[features]
fuzzing = ["arx-db/fuzzing"]
