[package]
name = "arx-framework"
description = "Arx stdlib"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
arx-aggregator = { workspace = true }
arx-crypto = { workspace = true, features = ["fuzzing"] }
arx-gas-algebra-ext =  { workspace = true }
arx-transaction-builder = { workspace = true }
arx-state-view = { workspace = true }
arx-types = { workspace = true }
base64 = { workspace = true }
bcs = { workspace = true }
better_any = { workspace = true }
blake2-rfc = { workspace = true }
clap = { workspace = true }
codespan-reporting = { workspace = true }
curve25519-dalek = { workspace = true }
flate2 = { workspace = true }
include_dir = { workspace = true }
itertools = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
move-binary-format = { workspace = true }
move-command-line-common = { workspace = true }
move-compiler ={ workspace = true }
move-core-types ={ workspace = true }
move-docgen ={ workspace = true }
move-model ={ workspace = true }
move-package ={ workspace = true }
move-prover ={ workspace = true }
move-prover-boogie-backend ={ workspace = true }
move-stackless-bytecode ={ workspace = true }
move-table-extension ={ workspace = true }
move-vm-runtime ={ workspace = true }
move-vm-types ={ workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand_core = { workspace = true }
rayon = { workspace = true }
ripemd = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
siphasher = { workspace = true }
smallvec = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tiny-keccak = { workspace = true }

[dev-dependencies]
arx-cached-packages = { workspace = true }
arx-gas = { workspace = true }
arx-vm = { workspace = true, features = ["testing"] }
claims = { workspace = true }
move-cli = { workspace = true }
move-prover = { workspace = true }
move-unit-test = { workspace = true }

[features]
default = []
fuzzing = ["arx-types/fuzzing", "proptest", "proptest-derive"]
testing = []

[lib]
doctest = false
